import Anthropic from '@anthropic-ai/sdk';

/**
 * @title ClaudeAuditor
 * @notice The "Risk Officer" Agent. Uses Claude 3.5 Sonnet to audit mandates generated by Gemini.
 * @dev "Gemini Proposes, Claude Disposes."
 */
export class ClaudeAuditor {
    private anthropic: Anthropic;

    constructor(apiKey: string) {
        this.anthropic = new Anthropic({
            apiKey: apiKey,
        });
    }

    /**
     * Audits a proposed mandate for risk, fraud, or policy violations.
     * @param mandate The JSON mandate object proposed by Gemini.
     * @param context Additional context (e.g., user prompt, negotiation logs).
     */
    async auditMandate(mandate: any, context: string): Promise<{ approved: boolean, reason: string }> {
        console.log("🧐 Claude Agent: Auditing mandate for risk...");

        const systemPrompt = `
            You are the Chief Risk Officer for an Autonomous Treasury.
            Your job is to audit transaction mandates proposed by another AI (Gemini).
            
            RULES:
            1. REJECT if the amount is > 1000 MNEE (Soft Cap for Demo).
            2. REJECT if the purpose is vague (e.g., "stuff", "misc").
            3. REJECT if the recipient looks suspicious.
            4. OTHERWISE, APPROVE.
            
            Return JSON: { "approved": boolean, "reason": "string" }
        `;

        const userMessage = `
            Proposed Mandate: ${JSON.stringify(mandate)}
            Context/User Request: "${context}"
        `;

        try {
            const msg = await this.anthropic.messages.create({
                model: "claude-3-5-sonnet-20240620",
                max_tokens: 1024,
                system: systemPrompt,
                messages: [{ role: "user", content: userMessage }],
            });

            // Extract text block efficiently (checking for type text)
            const textBlock = msg.content.find(c => c.type === 'text');
            if (!textBlock || textBlock.type !== 'text') throw new Error("No text response");

            let jsonStr = textBlock.text;
            // Clean markdown
            jsonStr = jsonStr.replace(/```json/g, '').replace(/```/g, '').trim();

            return JSON.parse(jsonStr);

        } catch (error) {
            console.error("Claude Audit Error:", error);
            // Fail safe: If Audit fails, we default to Reject for security
            return { approved: false, reason: "Audit System Offline (API Error)" };
        }
    }
}
