import { ethers } from "ethers";
import * as fs from 'fs';
import * as crypto from 'crypto';

/**
 * @title TLSVerifier
 * @notice Simulates the verification of a TLSNotary proof or ZK file.
 * @dev In a real production environment, this would verify the .json proof generated by the TLSNotary Prover.
 */
export class TLSVerifier {

    /**
     * Verifies that a file matches the commitment hash stored on-chain.
     * @param proofData The actual content/data being verified.
     * @param onChainCommitment The hash stored in the Escrow contract.
     */
    verifyProof(proofData: string, onChainCommitment: string): boolean {
        // Calculate hash of the data
        const hash = ethers.keccak256(ethers.toUtf8Bytes(proofData));

        console.log(`Verifying Proof...`);
        console.log(`Data Hash: ${hash}`);
        console.log(`Commitment: ${onChainCommitment}`);

        return hash === onChainCommitment;
    }

    /**
     * Generates a commitment hash for a file.
     * Use this when creating the Escrow.
     */
    generateCommitment(proofData: string): string {
        return ethers.keccak256(ethers.toUtf8Bytes(proofData));
    }
}
